version: '3'

services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=BloomBlog
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./.mysql_data:/var/lib/mysql


  Etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 2379:2379
    volumes:
      - ./.etcd-data:/bitnami/etcd  # 将主机的 ./etcd_data 文件夹映射为容器的数据库目录
