apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
spec:
  workspaces:
    - name: source
      description: Workspace containing the source code to build
  params:
    - name: repo-url
      description: Git repository URL
    - name: revision
      description: Git revision (branch/tag)
    - name: context
      description: Build context (e.g., directory containing Dockerfile)
    - name: image-name
      description: Name of the image to push
  steps:
    - name: git-clone
      image: alpine/git:latest
      script: |
        git clone -b $(params.revision) $(params.repo-url) /workspace/source
      volumeMounts:
        - name: source
          mountPath: /workspace/source
    - name: build-and-push
      image: quay.io/buildah/stable:latest
      script: |
        buildah bud --format=docker -t $(params.image-name) /workspace/source/$(params.context)
        buildah push $(params.image-name)
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-config
          mountPath: /root/.docker
  volumes:
    - name: docker-config
      secret:
        secretName: registry-bloomblog
