apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
spec:
  workspaces:
    - name: source
      description: Workspace containing the source code to build
  params:
    - name: repo-url
      description: Git repository URL
    - name: revision
      description: Git revision (branch/tag)
    - name: context
      description: Build context (e.g., directory containing Dockerfile)
    - name: image-name
      description: Name of the image to push
  steps:
    - name: git-clone
      image: alpine/git:latest
      script: |
        #!/bin/sh
        set -e
        echo "Cloning repository: $(params.repo-url) at revision: $(params.revision)"
        git clone -b $(params.revision) $(params.repo-url) /workspace/source
        echo "Repository cloned successfully."

    - name: build-and-push
      image: registry.fedoraproject.org/fedora:latest
      script: |
        #!/bin/sh
        set -e

        echo "Installing dependencies..."
        dnf install -y buildah curl jq tar gzip
        echo "Dependencies installed."

        echo "Reading DOCR credentials from /root/.docker/.dockerconfigjson"
        # 不要对挂载后的 .dockerconfigjson 再次 base64 解码，它已经是普通的 JSON 文件
        AUTH_VALUE=$(jq -r '.auths["registry.digitalocean.com"].auth' /root/.docker/.dockerconfigjson)
        if [ -z "$AUTH_VALUE" ] || [ "$AUTH_VALUE" = "null" ]; then
          echo "Failed to find auth for registry.digitalocean.com in .dockerconfigjson"
          exit 1
        fi

        # auth 字段本身是 base64 编码后的 "username:password"
        DO_API_TOKEN=$(echo "$AUTH_VALUE" | base64 -d | cut -d':' -f2)
        if [ -z "$DO_API_TOKEN" ]; then
          echo "Failed to extract DO_API_TOKEN from auth."
          exit 1
        fi
        echo "DO_API_TOKEN extracted successfully."

        echo "Installing doctl..."
        curl -fsSL https://github.com/digitalocean/doctl/releases/download/v1.120.0/doctl-1.120.0-linux-amd64.tar.gz | tar -xz -C /usr/local/bin
        echo "doctl installed."

        echo "Authenticating with DigitalOcean..."
        doctl auth init --access-token "${DO_API_TOKEN}"
        echo "Authentication successful."

        echo "Building the image..."
        buildah bud --format=docker -t $(params.image-name) -f /workspace/source/$(params.context)/Dockerfile /workspace/source
        echo "Image built successfully."

        echo "Pushing the image..."
        buildah push $(params.image-name)
        echo "Image pushed successfully."
      securityContext:
        privileged: true
      volumeMounts:
        - name: registry-bloomblog-secret
          mountPath: /root/.docker
  volumes:
    - name: registry-bloomblog-secret
      secret:
        secretName: registry-bloomblog
