apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
spec:
  workspaces:
    - name: source
      description: "Workspace containing the source code to build"
  params:
    - name: repo-url
    - name: revision
    - name: context
    - name: image-name
  steps:
    - name: git-clone
      image: alpine/git:latest
      script: |
        #!/bin/sh
        set -e
        echo "Cloning repository: $(params.repo-url) at revision: $(params.revision)"
        git clone -b $(params.revision) $(params.repo-url) /workspace/source
        echo "Repository cloned successfully."

    - name: prepare-build
      image: registry.fedoraproject.org/fedora:latest
      script: |
        #!/bin/sh
        set -e
        echo "Installing dependencies..."
        dnf install -y buildah curl tar gzip
        echo "Dependencies installed."

        echo "Setting up Docker config..."
        # 创建可写目录来存放 config.json
        mkdir -p /tmp/docker
        cp /root/.docker/.dockerconfigjson /tmp/docker/config.json

        # 告诉 buildah 使用此目录作为 Docker 配置目录
        export DOCKER_CONFIG=/tmp/docker

        echo "Building the image..."
        buildah bud --format=docker -t $(params.image-name) -f /workspace/source/$(params.context)/Dockerfile /workspace/source
        echo "Image built successfully."

        echo "Pushing the image..."
        buildah push $(params.image-name)
        echo "Image pushed successfully."
      securityContext:
        privileged: true
      volumeMounts:
        - name: registry-bloomblog-secret
          mountPath: /root/.docker
  volumes:
    - name: registry-bloomblog-secret
      secret:
        secretName: registry-blbg
