Global:
  Source: "config(local)"
  ChangeMe: "v3"

Etcd:
  Enable: true
  Address: "etcd"
  Port: 2379

Server:
  Name: "BloomBlogServer"
  Address: "0.0.0.0"
  Port: 8088

Hertz:
  UseNetpoll: true
  Http2:
    Enable: false
    DisableKeepalive: false
    ReadTimeout: "1m0s"
  Tls:
    Enable: false
    CertFile: ""
    KeyFile: ""
    ALPN: true

Client:
  Echo: true
  Foo: "bar"
  Servers:
    - "0.0.0.0"
