Global:
  Source: "config(local)"
  ChangeMe: "v3"
  DBType: "mysql"

Mysql:
  Host: "127.0.0.1"
  Port: 3306
  User: "root"
  Password: "123456"
  DBName: "BloomBlog"
  CharSet: "utf8mb4"
  ParseTime: true
  loc: "Local"
  maxIdleConns: 10
  maxOpenConns: 100