Global:
  Source: "config(local)"
  ChangeMe: "v3"



Etcd:
  Address: "0.0.0.0"
  Port: 2379

Server:
  Name: "BloomBlogFeedServer"
  Address: "0.0.0.0"
  Port: 8083

Client:
  Echo: true
  Foo: "bar"
  Servers:
    - "0.0.0.0"

