Global:
  Source: "config(local)"
  ChangeMe: "v3"

# Endpoint: 配置为运行minio服务的主机地址
Minio:
  Endpoint: 0.0.0.0:9000
  AccessKeyId: bloomblog
  SecretAccessKey: bloomblog
  UseSSL: false
  ImageBucketName : bloomblog-images