Global:
  Source: "config(local)"
  ChangeMe: "v3"

Etcd:
  Address: "127.0.0.1"
  Port: 2379

Server:
  Name: "TiktokPublishServer"
  Address: "127.0.0.1"
  Port: 8084

Client:
  Echo: true
  Foo: "bar"
  Servers:
    - "127.0.0.1"