apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: bloomblog-api
          image: bloomblog-api  # 改成你的镜像名称
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 30000  # 容器内部服务监听的端口
          resources:
            requests:
              cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8088         # 外部暴露的端口
      targetPort: 8088   # Pod 内的服务端口
      nodePort: 30000     # 直接使用 8101 端口作为 NodePort
  type: NodePort         # 使用 NodePort 直接暴露端口
