apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloomblog-favorite-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: favorite
  template:
    metadata:
      labels:
        app: favorite
    spec:
      containers:
        - name: bloomblog-favorite
          image: registry.digitalocean.com/bloomblog/bloomblog-favorite:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          resources:
            requests:
              cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: bloomblog-favorite-server
spec:
  selector:
    app: favorite
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: bloomblog-favorite-prometheus
spec:
  selector:
    app: favorite  # 确保与 Pod 的标签一致
  ports:
    - protocol: TCP
      port: 9091         # ClusterIP 暴露的端口
      targetPort: 9091   # Pod 内部的应用监听端口
  type: ClusterIP         # 使用 ClusterIP 类型