apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloomblog-favorite-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: favorite
  template:
    metadata:
      labels:
        app: favorite
    spec:
      containers:
        - name: bloomblog-favorite
          image: registry.digitalocean.com/bloomblog/bloomblog-favorite:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          resources:
            requests:
              cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: bloomblog-favorite-server
spec:
  selector:
    app: favorite
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP