apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloomblog-relation-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: relation
  template:
    metadata:
      labels:
        app: relation
    spec:
      containers:
        - name: bloomblog-relation
          image: registry.digitalocean.com/bloomblog/bloomblog-relation:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8087
          resources:
            requests:
              cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: bloomblog-relation-server
spec:
  selector:
    app: relation
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: bloomblog-relation-prometheus
spec:
  selector:
    app: relation  # 确保与 Pod 的标签一致
  ports:
    - protocol: TCP
      port: 9091         # ClusterIP 暴露的端口
      targetPort: 9091   # Pod 内部的应用监听端口
  type: ClusterIP         # 使用 ClusterIP 类型