apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  clusterIP: None  # 确保这一行存在
  ports:
    - port: 2379
      name: client
    - port: 2380
      name: peer
  selector:
    app: etcd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
spec:
  serviceName: etcd
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.9
          command:
            - /usr/local/bin/etcd
            - --name=$(POD_NAME)
            - --data-dir=/etcd-data
            - --listen-peer-urls=http://0.0.0.0:2380
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://$(POD_IP):2379
            - --initial-advertise-peer-urls=http://$(POD_IP):2380
            - --initial-cluster=$(POD_NAME)=http://$(POD_IP):2380
            - --initial-cluster-state=new
            - --initial-cluster-token=etcd-cluster
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 2379
              name: client
            - containerPort: 2380
              name: peer
          volumeMounts:
            - name: etcd-data
              mountPath: /etcd-data
      volumes:
        - name: etcd-data
          emptyDir: {}
