definitions:
  errno.ErrNo:
    properties:
      errCode:
        type: integer
      errMsg:
        type: string
    type: object
  favorite.BloomblogFavoriteActionResponse:
    properties:
      status_code:
        description: 状态码，0-成功，其他值-失败
        type: integer
      status_msg:
        description: 返回状态描述
        type: string
    type: object
  favorite.BloomblogFavoriteListResponse:
    properties:
      post_list:
        description: 用户点赞视频列表
        items:
          $ref: '#/definitions/feed.Post'
        type: array
      status_code:
        description: 状态码，0-成功，其他值-失败
        type: integer
      status_msg:
        description: 返回状态描述
        type: string
    type: object
  feed.BloomblogFeedResponse:
    properties:
      next_time:
        description: 返回的帖子中最早的时间，用于下次请求
        type: integer
      post_list:
        description: 帖子列表
        items:
          $ref: '#/definitions/feed.Post'
        type: array
      status_code:
        description: 状态码，0-成功，其他值-失败
        type: integer
      status_msg:
        description: 返回状态描述
        type: string
    type: object
  feed.Post:
    properties:
      author:
        allOf:
        - $ref: '#/definitions/user.User'
        description: 发帖用户信息
      comment_count:
        description: 评论总数
        type: integer
      cover_url:
        type: string
      id:
        description: 帖子唯一标识
        type: integer
      image_urls:
        description: 帖子的图片地址列表
        items:
          type: string
        type: array
      is_liked:
        description: 当前用户是否已点赞
        type: boolean
      like_count:
        description: 点赞总数
        type: integer
      modified_at:
        description: 帖子的修改时间
        type: integer
      text_content:
        description: 帖子的文字内容
        type: string
      title:
        description: 帖子标题
        type: string
    type: object
  handlers.FavoriteActionParam:
    properties:
      action_type:
        description: 1-点赞，2-取消点赞
        type: integer
      post_id:
        description: 视频id
        type: integer
      token:
        description: 用户鉴权token
        type: string
      user_id:
        description: 用户id
        type: integer
    type: object
  handlers.RelationActionParam:
    properties:
      action_type:
        description: 1-关注，2-取消关注
        type: integer
      to_user_id:
        description: 对方用户id
        type: integer
      token:
        description: 用户鉴权token
        type: string
      user_id:
        description: 用户id
        type: integer
    type: object
  handlers.UserRegisterParam:
    properties:
      password:
        description: 用户密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  publish.BloomblogPublishActionResponse:
    properties:
      status_code:
        description: 状态码，0-成功，其他值-失败
        type: integer
      status_msg:
        description: 返回状态描述
        type: string
    type: object
  relation.BloomblogRelationActionResponse:
    properties:
      status_code:
        description: 0-success，others-failure
        type: integer
      status_msg:
        description: return statement description
        type: string
    type: object
  relation.BloomblogRelationFollowListResponse:
    properties:
      status_code:
        description: 0-success others-failure
        type: integer
      status_msg:
        description: status description
        type: string
      user_list:
        description: user list
        items:
          $ref: '#/definitions/user.User'
        type: array
    type: object
  relation.BloomblogRelationFollowerListResponse:
    properties:
      status_code:
        type: integer
      status_msg:
        type: string
      user_list:
        items:
          $ref: '#/definitions/user.User'
        type: array
    type: object
  user.BloomBlogUserRegisterResponse:
    properties:
      status_code:
        description: status code, 0 for success, others for failure
        type: integer
      status_msg:
        description: description for status
        type: string
      token:
        description: credential token
        type: string
      user_id:
        description: user id
        type: integer
    type: object
  user.BloomBlogUserResponse:
    properties:
      status_code:
        description: status code, 0 for success, others for failure
        type: integer
      status_msg:
        description: description for status
        type: string
      user:
        allOf:
        - $ref: '#/definitions/user.User'
        description: user information
    type: object
  user.User:
    properties:
      follow_count:
        description: follow count
        type: integer
      follower_count:
        description: followers count
        type: integer
      id:
        description: user id
        type: integer
      is_follow:
        description: true-followed，false-not followed
        type: boolean
      name:
        description: user name
        type: string
    type: object
info:
  contact: {}
paths:
  /bloomblog/favorite/action:
    post:
      consumes:
      - application/json
      description: This endpoint allows a user to favorite or unfavorite a post. The
        user must provide a valid JWT token in the Authorization header.
      parameters:
      - description: Favorite Action Parameters
        in: body
        name: FavoriteAction
        required: true
        schema:
          $ref: '#/definitions/handlers.FavoriteActionParam'
      produces:
      - application/json
      responses:
        "200":
          description: Action performed successfully
          schema:
            $ref: '#/definitions/favorite.BloomblogFavoriteActionResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/favorite.BloomblogFavoriteActionResponse'
        "401":
          description: Unauthorized, invalid token
          schema:
            $ref: '#/definitions/favorite.BloomblogFavoriteActionResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/favorite.BloomblogFavoriteActionResponse'
      security:
      - BearerAuth: []
      summary: Perform favorite action on a post
      tags:
      - favorite
  /bloomblog/favorite/list:
    get:
      consumes:
      - application/json
      description: retrieve the favorite list of a user
      parameters:
      - description: userid
        in: query
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Action performed successfully
          schema:
            $ref: '#/definitions/favorite.BloomblogFavoriteListResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/favorite.BloomblogFavoriteListResponse'
        "401":
          description: Unauthorized, invalid token
          schema:
            $ref: '#/definitions/favorite.BloomblogFavoriteListResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/favorite.BloomblogFavoriteListResponse'
      security:
      - BearerAuth: []
      summary: retrieve the favorite list of a user
      tags:
      - favorite
  /bloomblog/feed/getfeed:
    get:
      consumes:
      - application/json
      description: This endpoint allows users to fetch feed data using the latest
        timestamp and an optional authentication token.
      parameters:
      - description: The timestamp for the latest feed item (optional). Defaults to
          now if not provided.
        in: query
        name: latest_time
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation, returns the feed data.
          schema:
            $ref: '#/definitions/feed.BloomblogFeedResponse'
        "400":
          description: Invalid input data, such as malformed timestamp.
          schema:
            $ref: '#/definitions/feed.BloomblogFeedResponse'
        "500":
          description: Internal server error.
          schema:
            $ref: '#/definitions/feed.BloomblogFeedResponse'
      security:
      - BearerAuth: []
      summary: Retrieve feed
      tags:
      - feed
  /bloomblog/publish/action:
    post:
      consumes:
      - multipart/form-data
      description: This endpoint allows users to publish a blog post with images,
        title, and content.
      parameters:
      - description: The title of the blog post
        in: formData
        name: title
        required: true
        type: string
      - description: The content of the blog post
        in: formData
        name: content
        required: true
        type: string
      - description: Multiple image files (repeatable), upload all images as part
          of 'images' field
        in: formData
        name: images
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: The response object
          schema:
            $ref: '#/definitions/publish.BloomblogPublishActionResponse'
        "400":
          description: Invalid input data
          schema:
            $ref: '#/definitions/publish.BloomblogPublishActionResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/publish.BloomblogPublishActionResponse'
      security:
      - BearerAuth: []
      summary: Publish a blog post
      tags:
      - publish
  /bloomblog/relation/action:
    post:
      consumes:
      - application/json
      description: Handles actions like follow, unfollow, or other user relation actions.
      parameters:
      - description: Relation Action Parameters
        in: body
        name: relationAction
        required: true
        schema:
          $ref: '#/definitions/handlers.RelationActionParam'
      produces:
      - application/json
      responses:
        "200":
          description: Action completed successfully
          schema:
            $ref: '#/definitions/relation.BloomblogRelationActionResponse'
        "400":
          description: Invalid input parameters
          schema:
            $ref: '#/definitions/relation.BloomblogRelationActionResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/relation.BloomblogRelationActionResponse'
      security:
      - BearerAuth: []
      summary: Perform a relation action
      tags:
      - Relation
  /bloomblog/relation/followerlist:
    get:
      consumes:
      - application/json
      description: Retrieves the list of users that follow the specified user.
      parameters:
      - description: The ID of the user to retrieve the follower list for
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved follower list
          schema:
            $ref: '#/definitions/relation.BloomblogRelationFollowerListResponse'
        "400":
          description: Invalid input parameters
          schema:
            $ref: '#/definitions/relation.BloomblogRelationFollowerListResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/relation.BloomblogRelationFollowerListResponse'
      security:
      - BearerAuth: []
      summary: Get follower list
      tags:
      - Relation
  /bloomblog/relation/followlist:
    get:
      consumes:
      - application/json
      description: Retrieves the list of users that a specific user is following.
      parameters:
      - description: The ID of the user to retrieve the following list for
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved following list
          schema:
            $ref: '#/definitions/relation.BloomblogRelationFollowListResponse'
        "400":
          description: Invalid input parameters
          schema:
            $ref: '#/definitions/relation.BloomblogRelationFollowListResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/relation.BloomblogRelationFollowListResponse'
      security:
      - BearerAuth: []
      summary: Get following list
      tags:
      - Relation
  /bloomblog/user/getuserbyid:
    get:
      consumes:
      - application/json
      description: Get user information by ID and token
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.BloomBlogUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errno.ErrNo'
      security:
      - BearerAuth: []
      summary: Get User by ID
      tags:
      - User
  /bloomblog/user/login:
    post:
      consumes:
      - application/json
      description: Authenticate user with username and password
      parameters:
      - description: User login data
        in: body
        name: loginParam
        required: true
        schema:
          $ref: '#/definitions/handlers.UserRegisterParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.BloomBlogUserRegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errno.ErrNo'
      summary: User Login
      tags:
      - User
  /bloomblog/user/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User registration data
        in: body
        name: registerParam
        required: true
        schema:
          $ref: '#/definitions/handlers.UserRegisterParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.BloomBlogUserRegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errno.ErrNo'
      summary: User Registration
      tags:
      - User
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
