name: Trigger Tekton PipelineRun on DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  trigger-tekton-pipeline:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout 仓库代码
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: 安装 doctl 和 kubectl
      - name: Install doctl and kubectl
        run: |
          sudo snap install doctl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # Step 3: 配置 doctl 并初始化凭据
      - name: Authenticate with DigitalOcean
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        run: |
          doctl auth init --access-token "${DIGITALOCEAN_ACCESS_TOKEN}"
          doctl kubernetes cluster kubeconfig save ${{ secrets.CLUSTER_NAME }}

      # Step 4: 查看 Kubernetes 集群信息
      - name: Verify Kubernetes Connection
        run: |
          kubectl cluster-info

      # Step 5: 应用 Tekton Task 和 Pipeline 定义
      - name: Apply Tekton Task
        run: |
          kubectl apply -f .github/ci/build-and-push.yaml

      - name: Apply Tekton Pipeline
        run: |
          kubectl apply -f .github/ci/multi-service-pipeline.yaml

      # Step 6: 触发 Tekton PipelineRun
      - name: Trigger Tekton PipelineRun
        run: |
          kubectl apply -f .github/ci/multi-service-pipeline-run.yaml

      # Step 7: 查看 PipelineRun 状态
      - name: Check PipelineRun Status
        run: |
          kubectl get pipelinerun -o wide
