name: Trigger Tekton PipelineRun on DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  trigger-tekton-pipeline:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout 仓库代码
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: 安装 doctl 非 Snap 版本和 kubectl
      - name: Install doctl and kubectl
        run: |
          curl -L -o doctl.tar.gz "https://github.com/digitalocean/doctl/releases/download/v1.100.0/doctl-1.100.0-linux-amd64.tar.gz"
          tar -xvf doctl.tar.gz
          sudo mv doctl /usr/local/bin/
          doctl version

          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # Step 3: 初始化 doctl 并保存 kubeconfig
      - name: Authenticate with DigitalOcean
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        run: |
          doctl auth init --access-token "${DIGITALOCEAN_ACCESS_TOKEN}"
          doctl kubernetes cluster kubeconfig save ${{ secrets.CLUSTER_NAME }}
          export KUBECONFIG=~/.kube/config
          kubectl cluster-info

      # Step 4: 应用 Tekton Task 和 Pipeline 定义
      - name: Apply Tekton Task
        run: |
          kubectl apply -f .github/ci/build-and-push.yaml

      - name: Apply Tekton Pipeline
        run: |
          kubectl apply -f .github/ci/multi-service-pipeline.yaml

      # Step 5: 触发 Tekton PipelineRun
      - name: Trigger Tekton PipelineRun
        run: |
          kubectl apply -f .github/ci/multi-service-pipeline-run.yaml

      # Step 6: 查看 PipelineRun 状态
      - name: Check PipelineRun Status
        run: |
          kubectl get pipelinerun -o wide
